name: DEPLOYMENT PRODUCTION ASIC GUANIPA WEB

on:
  push:
    tags:
      - "*"
      - "!*alpha*"
      - "!*beta*"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FLUTTER_ENV: production
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Set enviroment .env
        run: |
          :> .env
          echo "VERSION=${{ github.ref_name }}" >> .env
          echo "API_URL=${{ secrets.API_URL }}" >> .env
      - name: Install Dependencies
        run: |
          flutter pub get
      - name: Build Flutter Web
        run: flutter build web --release

      - name: docker build
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:${{ github.ref_name }} .

      - name: login docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_USER_TOKEN }}

      - name: docker push
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:${{ github.ref_name }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            CONTAINER=asic-guanipa-web \
            TAG=${{ github.ref_name }} \
            IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }} \
            /app/create-container \
            --restart unless-stopped \
            --network asic-guanipa-network \
            -e PORT=4000
