name: DEPLOYMENT PRODUCTION ASIC GUANIPA WEB

on:
  push:
    tags:
      - "*"
      - "!*alpha*"
      - "!*beta*"
    branches:
      - feature/cd

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FLUTTER_ENV: "${{ secrets.FLUTTER_ENV }}"
      API_URL: "${{ secrets.API_URL }}"
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build Flutter Web
        run: flutter build web --release

      - name: docker build
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:dev .

      - name: login docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_USER_TOKEN }}

      - name: docker push
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:dev

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            CONTAINER=asic-guanipa-web \
            TAG=dev \
            IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }} \
            /app/create-container \
            --restart unless-stopped \
            --network asic-guanipa-network \
            -e PORT=4000
